artifact_uri: /Users/lucasbagge/Documents/Projects/aarhus-dv/business scienence io/lab_39_mlflow/lab-39/1/7a82811693a54629bcb2003f764382b1/artifacts
end_time: 1621345083833
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 7a82811693a54629bcb2003f764382b1
run_uuid: 7a82811693a54629bcb2003f764382b1
source_name: ''
source_type: 4
source_version: ''
start_time: 1621345056786
status: 3
tags: []
user_id: lucasbagge
