artifact_uri: /Users/lucasbagge/Documents/Projects/aarhus-dv/business scienence io/lab_39_mlflow/lab-39/1/efa57bf0baf14aa3bad0e433dd8c8c85/artifacts
end_time: 1621345803822
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: efa57bf0baf14aa3bad0e433dd8c8c85
run_uuid: efa57bf0baf14aa3bad0e433dd8c8c85
source_name: ''
source_type: 4
source_version: ''
start_time: 1621345763520
status: 3
tags: []
user_id: lucasbagge
