---
title: "Aflevering 1"
subtitle: "Lucas Bagge"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
```




```{python}
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
```


## a) Vælg nogle rimelige værdier for indgangerne i a, b, c og d, og brug derefter

I den første del af opgave skal vi replikerer den angivet plot. Her opskriver
jeg nogle x og y koordinater og ganger indgangene vektorerne; a, b, c og d.

```{python}
O = np.array([0, 0])
A = np.array([1, 3,])
B = np.array([1.5, 3.2])
C = np.array([1.56, 2.2])
P = np.array([1.52, 1.8])
o = O
a = A
b = B - A
c = C - B
p = P - C
x = np.array([0, 1, 1.5, 1.56, 1.52])
y = np.array([0, 3, 3.2, 2.2, 1.8])
fig, ax = plt.subplots()
ax.plot(x,y, marker = 'o')
plt.show()
```

### b) Bestem vektoren $\bar OP$ ud fra a,b, c og d.

Her benytter jeg af en angivet formel fra notesæt 2:

$$
|\bar OP|=r=\sqrt(x^2 + ý^2)
$$

```{python}
OP = a + b + c + p
```


Vi kan bruge numpy `np.linalg.norm` til dette formål

```{python}
print("Længden er:", '%.3g' % OP )
```

### c) Vis at c bøjes med en rotationsmatrix


```{python}
fig, ax = plt.subplots()
ax.plot(x, y, marker = 'o')
fig.show()
```

```{python}
def rotatation(x,y,c,s):
    return c * x + s * y, s * y - c * y 

c, s = 0.4, np.sqrt(0.84)

r1x, r1y = rotatation(x, y, c, s)

a = 1.0
b = 0.5
c = 0.5
d = 0.50
fig, ax = plt.subplots()
ax.plot(d*x + d*y, y  , marker = 'o')
```


I ovenstående graf har jeg forsøgt at vise:

$$
bøj_C(s)=[a|b|c|R_C d]
$$

I mit plot har jeg anvendt værdien `d` på min matrix og ser at vi har en stor rotation i B og C leddet.
Jeg har ikke kunne isoler en effekt alene på C leddet, men dog kan vi se at når vi anvende en rotationsmatrix $R_C$ så bøjer C leddet sig også.

### d) Giv en opskrift for bøjA, armen kun bøjes i A.

Her kan vi skrive følgende rotationmatrix formel opskrift

$$
bøj_A(S)=[R_A a|b|c| d]
$$

```{python}
a = 0.3
b = 0.7
c = 0.7
d = 0.3
fig, ax = plt.subplots()
ax.plot(x, a*x**2 + y,  marker = 'o')
```


I ovenstående har jeg forsægt at bøje A leddet alene.

### e) Vis det generelle udtyk at der ingen betydning er på hvilket led man bøjer først.

Vi får af vide at S er en matrix og således er $bøj_A$ en skalar man ganger på, så vi kan simpel vise nogle af matrix regne regler:

$$
bøj_A(bøj_C(S))
$$

Af definitionen af skalar produkt kan vie skrive

$$
bøj_A(bøj_C\cdot S)
$$

$$
(bøj_A\cdot bøj_C) \cdot S
$$

$$
bøj_C (bøj_A \cdot S)
$$

Som giver det ønskede resultat og viser at det ikke har en betydning for hvilket led vi bøjer først. 
