artifact_uri: /Users/lucasbagge/Documents/Projects/aarhus-dv/business scienence io/lab_40_docker/mlflow/1/a264825e773b4821abc895e33d4fb424/artifacts
end_time: 1621720361537
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: a264825e773b4821abc895e33d4fb424
run_uuid: a264825e773b4821abc895e33d4fb424
source_name: ''
source_type: 4
source_version: ''
start_time: 1621720332298
status: 3
tags: []
user_id: lucasbagge
