---
title: "Bankruptcy Classifier"
subtitle: "MLflow Tracking & APIs"
author: "Business Science"
date: "7/22/2020"
output: 
    html_document:
        theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    message = FALSE, 
    warning = FALSE,
    root.dir = rprojroot::find_rstudio_root_file()
)
```

# Libraries

```{r}
# MLflow
library(mlflow)
library(carrier)
library(jsonlite)
library(fs)

# Machine Learning
library(h2o)

# EDA
library(correlationfunnel)
library(DataExplorer)

# Core
library(tidyverse)
library(tidyquant)
```




# Data

## Bankruptcy Data
```{r}
bankruptcy_data_tbl <- read_rds("00_data/bankruptcy_data.rds")
bankruptcy_data_tbl
```

## Dictionary

```{r}
data_dictionary_raw_tbl <- read_rds("00_data/data_dictionary_raw_tbl.rds")
data_dictionary_raw_tbl
```

```{r, paged.print = FALSE}
data_dictionary_tbl <- data_dictionary_raw_tbl %>%
    separate(
        `Attribute.Information:`, 
        into = c("id", "desc"),
        sep = " ", 
        extra = "merge"
    ) %>%
    mutate(id = str_replace(id, "X", "Attr"))

data_dictionary_tbl
```


# EDA

```{r}
plot_intro(bankruptcy_data_tbl)
```

```{r}
plot_missing(bankruptcy_data_tbl, missing_only = TRUE)
```

```{r}
data_dictionary_tbl %>% filter(id == "Attr37")
```

```{r}
data_prepared_tbl <- bankruptcy_data_tbl %>%
    select(-Attr37) %>%
    drop_na()

data_prepared_tbl
```

# Features Analysis

```{r}
data_prepared_tbl %>%
    binarize() %>%
    correlate(class__1) %>%
    mutate(feature_desc = feature %>% VLOOKUP(data_dictionary_tbl, id, desc)) %>%
    mutate(feature_desc = ifelse(is.na(feature_desc), "", feature_desc)) %>%
    mutate(feature = str_c(as.character(feature), ": ", feature_desc)) %>%
    mutate(feature = as_factor(feature) %>% fct_rev()) %>%
    select(-feature_desc) %>%
    plot_correlation_funnel(interactive = TRUE)
```



# Machine Learning

### H2O Setup

```{r}
h2o.init()
```



```{r}
y <- "class"
x <- setdiff(names(data_prepared_tbl), y)
```


### Random Forest

```{r}
model_rf_h2o <-
    h2o.randomForest(
        x = x, 
        y = y, 
        training_frame = as.h2o(data_prepared_tbl), 
        
        ntrees    = 50,
        max_depth = 10, 
        
        nfolds    = 5,
        seed      = 123
    )
```

```{r, paged.print = F}
model_rf_h2o %>% h2o.performance(xval = TRUE)
```

## Variable Importance Plot

```{r}
h2o.varimp_plot(model_rf_h2o)
```



## Making Predictions

```{r}
sample_tbl <- 
    data_prepared_tbl %>%
    filter(class == "1") %>%
    slice(1) 

sample_tbl
```

```{r}
as.data.frame(h2o.predict(model_rf_h2o, as.h2o(sample_tbl %>% select(-class))))
```

```{r, paged.print = FALSE}
model_rf_h2o
```

# Experiment Tracking with MLflow

## MLflow Setup

```{r}
mlflow_set_tracking_uri("lab-39")

mlflow_get_tracking_uri()
```


```{r}
experiment_name <- "bankruptcy_prediction"

# mlflow_create_experiment(experiment_name)

mlflow_set_experiment(experiment_name)

mlflow_get_experiment()
```

## MLFlow UI

```{r}
mlflow_ui()
```


## MLFlow Tracking 

```{r}
# Variable Parameters to Log Models for
n_trees   <- 100
max_depth <- 10
```

```{r}
with(mlflow_start_run(), {
    
    # Create Model
    model <- h2o.randomForest(
        x = x, 
        y = y, 
        training_frame = as.h2o(data_prepared_tbl), 
        ntrees    = n_trees,
        max_depth = max_depth, 
        nfolds    = 5, 
        seed      = 123 
    )
    
    # Save Model
    path <- "temp/"
    file <- model@model_id
    full_path <- str_c(path, file)
    h2o.saveModel(model, path = path, force = TRUE) # Save in temp location
    
    # Create predictor
    predictor_crate  <- crate(~ as.data.frame(h2o::h2o.predict(!!model, h2o::as.h2o(.x))), !!model)
    
    # Calculate Metrics
    auc     <- h2o.auc(model, xval = TRUE)
    aucpr   <- h2o.aucpr(model, xval = TRUE)
    logloss <- h2o.logloss(model, xval = TRUE)
    
    # LOGS
    mlflow_log_param("n_trees", n_trees)
    mlflow_log_param("max_depth", max_depth)
    
    mlflow_log_metric("auc", auc)
    mlflow_log_metric("aucpr", aucpr)
    mlflow_log_metric("logloss", logloss)
    
    mlflow_log_model(model = predictor_crate, artifact_path = "predictor")
    mlflow_log_artifact(path = full_path, artifact_path = "h2o")
    
    # Cleanup - Remove model from temp folder
    fs::file_delete(full_path)
})
```

# Swagger API (Predictions in Production)

## Create JSON

```{r}
sample_tbl %>% toJSON() %>% prettify()
```

## Bonus Script - Serve H2O Model with MLFlow

```{r}
# Loads serve_model()
source("llpro_bonus_swagger_api.R")
```

## Serve Model & Test Server

```{r}
serve_model(
    uri_name      = "lab-39/",
    experiment_id = "1",
    run_id        = "efa57bf0baf14aa3bad0e433dd8c8c85"
)
```



