artifact_uri: /Users/lucasbagge/Documents/Projects/aarhus-dv/business scienence io/lab_40_docker/mlflow/1/77d454f9fd0f45cbb2f3673df2c69cd5/artifacts
end_time: 1621720386761
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 77d454f9fd0f45cbb2f3673df2c69cd5
run_uuid: 77d454f9fd0f45cbb2f3673df2c69cd5
source_name: ''
source_type: 4
source_version: ''
start_time: 1621720361863
status: 3
tags: []
user_id: lucasbagge
