---
title: "Week 9 - Kernel regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
library(tidyverse)
```

## Load data

Get the data.

```{python}
# Dependencies
import numpy as np
import scipy
from sklearn.datasets import load_boston
from sklearn.decomposition import PCA 
import matplotlib.pyplot as plt 
import seaborn as sns

dataset = load_boston()
x = dataset.data[:,12] # LSTAT: % lower status of the population.
t = dataset.target # MEDV: Median value of owner-occupied homes in $1000s.

def plot_scatter(data, target, alpha=0.5, legend=True):
    scatter = plt.scatter(data, target,  edgecolor='none', alpha=alpha)
    plt.xlabel('x')
    plt.ylabel('t')

# Let's plot all the data in 2D
plot_scatter(x, t)
plt.show()
```

Use `reticulate` to get the data in R.

```{r}
x_r <- py$x %>% as.numeric()
t_r <- py$t %>% as.numeric()
```


## Modelleing

Use **Nadaraya-Watson**:

```{r}
# A naive implementation of the Nadaraya-Watson estimator
mNW <- function(x, X, Y, sigma, K = dnorm) {

  # Arguments
  # x: evaluation points
  # X: vector (size n) with the predictors
  # Y: vector (size n) with the response variable
  # h: bandwidth
  # K: kernel

  # Matrix of size n x length(x)
  Kx <- sapply(X, function(Xi) 
                  K( -exp( ( (x - Xi)^2 / 2*sigma^2) ) )
               )

  # Weights
  W <- Kx / rowSums(Kx) # Column recycling!

  # Means at x ("drop" to drop the matrix attributes)
  drop(W %*% Y)

}

xGrid <- seq(-50, 50, l = 500)

fit = lm(t_r ~ x_r)

plot(x_r, 
     t_r, 
     pch=20)
abline(fit, lwd = 2, col="red")
lines(xGrid, 
      mNW(x = xGrid, X = x_r, Y = t_r, sigma = 1),
      col = "blue",
      lty = 2,
      lwd = 3)
lines(xGrid, 
      mNW(x = xGrid, X = x_r, Y = t_r, sigma = 2),
      col = "orange",
      lty = 3, 
      lwd = 3)
lines(xGrid, 
      mNW(x = xGrid, X = x_r, Y = t_r, sigma = 10),
      col = "purple", 
      lty = 4, 
      lwd = 3)


legend("topright",
       c("Linear regression",
         "Kernal regression (1)",
         "Kernal regression (2)",
         "Kernal regression (10)"),
       lty = c(1, 2, 3, 4),
       col=c("red", "blue", "orange","purple"),
       bg = "white" )
```

