artifact_uri: /Users/lucasbagge/Documents/Projects/aarhus-dv/business scienence io/lab_40_docker/mlflow/1/1d50ae78d91c4502ba7c65b07d5f5909/artifacts
end_time: 1621720469150
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 1d50ae78d91c4502ba7c65b07d5f5909
run_uuid: 1d50ae78d91c4502ba7c65b07d5f5909
source_name: ''
source_type: 4
source_version: ''
start_time: 1621720426579
status: 3
tags: []
user_id: lucasbagge
