artifact_uri: /Users/lucasbagge/Documents/Projects/aarhus-dv/business scienence io/lab_40_docker/mlflow/1/042163c13a874076a9c6bef64b0b9915/artifacts
end_time: 1621720426261
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 042163c13a874076a9c6bef64b0b9915
run_uuid: 042163c13a874076a9c6bef64b0b9915
source_name: ''
source_type: 4
source_version: ''
start_time: 1621720387022
status: 3
tags: []
user_id: lucasbagge
