artifact_uri: /Users/lucasbagge/Documents/Projects/aarhus-dv/business scienence io/lab_39_mlflow/lab-39/1/c5dd963994a24a28a161447795e88711/artifacts
end_time: 1621345494958
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: c5dd963994a24a28a161447795e88711
run_uuid: c5dd963994a24a28a161447795e88711
source_name: ''
source_type: 4
source_version: ''
start_time: 1621345475018
status: 3
tags: []
user_id: lucasbagge
