artifact_uri: /Users/lucasbagge/Documents/Projects/aarhus-dv/business scienence io/lab_39_mlflow/lab-39/1/4c9353ff64b347ef8f8a9f70d776f733/artifacts
end_time: 1621541203363
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 4c9353ff64b347ef8f8a9f70d776f733
run_uuid: 4c9353ff64b347ef8f8a9f70d776f733
source_name: ''
source_type: 4
source_version: ''
start_time: 1621541150007
status: 3
tags: []
user_id: lucasbagge
