---
htitle: "Untitled"
output: html_document
---

## lib

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("caret")
library("corrplot")
library("forecast")
library("kernlab")
library("neuralnet")
library("PerformanceAnalytics")
library("quantmod")
library("tseries")
library(tidymodels)
library(tidyverse)
library(tidyquant)
library("xgboost")
library(timetk)
library(gtsummary)
library(modeltime)
library(timetk)
library(tidymodels)
options(scipen = 999)
library(gtsummary)
library(corrr)
```

## Target features


### tidy

```{r}
spy_tiblle <- tq_get("SPY",
                     get = "stock.prices",
                     from="2007-01-01",
                     to="2017-01-01") %>% 
  tq_mutate(select = adjusted, dailyReturn, type = "log") %>% 
  tq_mutate(select = daily.returns, Lag, k = 1:9) %>% 
  select(date, daily.returns, starts_with("Lag")) %>% 
  na.omit()

rspyt_tibble <- spy_tiblle %>%
  filter(date <= "2014-01-01")

rspyf_tibble <- spy_tiblle %>%
  filter(date >=  "2014-01-01" & date <= "2016-01-01")

rspyp_tibble <- spy_tiblle %>% 
  filter(date >=  "2009-01-15" & date <= "2016-01-01")

```

## Predictor Features selection

### tidy

```{r}
lmta_tibble <-
  linear_reg() %>% 
  set_engine('lm') %>% # adds lm implementation of linear regression
  set_mode('regression') %>% 
  fit(rspyt_tibble$daily.returns ~ Lag.1+Lag.2+Lag.3+Lag.4+Lag.5+Lag.6+Lag.7+
        Lag.8+Lag.9, 
      data = rspyt_tibble)


lmtb_tibble <-
  linear_reg() %>% 
  set_engine('lm') %>% # adds lm implementation of linear regression
  set_mode('regression') %>% 
  fit(rspyt_tibble$daily.returns ~ Lag.1+Lag.2 +Lag.5,
      data = rspyt_tibble)

tidy(lmtb_tibble)

lmta_tibble %>% tbl_regression()

x <- correlate(rspyt_tibble %>% select(-date))
x %>% fashion(decimals = 3)
network_plot(x, min_cor = .7, colors = c("red", "green"), legend = TRUE)
rplot(x)

# 4.6.1. Principal Component Analysis tibble
# https://clauswilke.com/blog/2020/09/07/pca-tidyverse-style/
rspyt_fit <-
  rspyt_tibble %>% 
  select(where(is.numeric)) %>% # retain only numeric columns
  prcomp(scale = TRUE) # do PCA on scaled data

rspyt_fit %>% 
  tidy(matrix = "rotation")

rspyt_fit %>% 
  tidy(matrix = "eigenvalues") %>% 
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) +
  theme_minimal()
```



## Algorithm Training 

### 1) Split data

```{r}
df <- spy_tiblle %>% select(date, daily.returns, Lag.1, Lag.2, Lag.5)
splits <- time_series_split(df, assess = "2 years", cumulative = TRUE)

train <- training(splits)
test <- testing(splits)
```


### 2) Feature enginerring

```{r}
rec <-
  recipe(train, daily.returns ~ .) 
```


### 3) Model

```{r}
model_fit_arima <- 
  arima_reg() %>%
  set_engine(engine = "auto_arima") %>%
  fit(daily.returns ~ ., data = training(splits)
  )

model_spec_xgboost <- 
  boost_tree(trees = 100, 
             mode = "regression") %>%
  set_engine("xgboost")

wflw_fit_mars <- 
  workflow() %>%
  add_recipe(rec %>% step_rm(date)) %>%
  add_model(model_spec_xgboost) %>%
  fit(training(splits))

model_spec_nnetar <- 
  nnetar_reg() %>%
  set_engine("nnetar") %>% 
  set_mode("regression")

wflw_fit_nnetar <- 
  workflow() %>%
  add_recipe(rec ) %>%
  add_model(model_spec_nnetar) %>%
  fit(training(splits))


models_tbl <- modeltime_table(
  model_fit_arima,
  wflw_fit_mars,
  wflw_fit_nnetar
)

calibration_tbl <- models_tbl %>%
  modeltime_calibrate(new_data = testing(splits))
```


### 4) get result

```{r}
calibration_tbl_results <- 
  calibration_tbl %>%
  modeltime_accuracy()

calibration_tbl_results
```

```{r}
calibration_tbl %>%
  modeltime_forecast(
    new_data    = testing(splits),
    actual_data = df
  )  %>% 
  plot_modeltime_forecast(
    .legend_max_width = 25, # For mobile screens
    .interactive      = TRUE
  )
```


### 5) Trading strategy

### 6) Forecast

```{r}
refit_tbl <- 
  calibration_tbl %>%
  modeltime_refit(data = df)

refit_tbl %>%
  modeltime_forecast(h = "3 years", 
                     actual_data = df) %>%
  plot_modeltime_forecast(
    .legend_max_width = 25, # For mobile screens
    .interactive      = TRUE
  )
```


## Machine Trading Strategies

### tidy

```{r}
test_test <- predict(spec, test) 

xgbmi_tibble <- 
  predict(spec, test) %>% 
  bind_cols(date = test$date) %>% 
  filter(date > '2016-01-04') %>% 
  mutate(xgbmsig = case_when(
    Lag(.pred) < 0 & .pred > 0 ~ 1,
    Lag(.pred) > 0 & .pred < 0 ~ -1,
    TRUE ~ 0))
```

